"use client"

import { ChorbieChat } from '@/components/ui/chorbit-chat'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

export default function ChorbieDemo() {
  const mockUser = {
    id: 'demo-child',
    name: 'Demo Kid',
    role: 'CHILD' as const,
    weeklyEarnings: 12.50,
    completionRate: 85
  }

  const mockChores = [
    { id: '1', title: 'Make Bed', reward: 2, estimatedMinutes: 5, isRequired: true },
    { id: '2', title: 'Clean Room', reward: 5, estimatedMinutes: 30, isRequired: false },
    { id: '3', title: 'Take Out Trash', reward: 3, estimatedMinutes: 10, isRequired: true },
    { id: '4', title: 'Help with Dishes', reward: 4, estimatedMinutes: 15, isRequired: false }
  ]

  const handleScheduleGenerated = (schedule: any) => {
    console.log('🎉 Schedule generated by Chorbie:', schedule)
    alert(`Chorbie created a schedule: "${schedule.title}" with ${schedule.tasks.length} tasks!`)
  }

  const handleExportRequest = async (schedule: any) => {
    console.log('📱 Export requested for schedule:', schedule)
    alert(`Exporting "${schedule.title}" to iPhone calendar! 📅`)
    
    // For demo purposes, we'll just log it
    // In production, this would trigger the actual export
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-50 p-6">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            🤖 Meet Chorbie AI
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Your friendly AI assistant for chores and time management. 
            Ask Chorbie to help you plan your day, get motivation, or export schedules to your iPhone!
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Demo Info */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <span>👋</span>
                  <span>Try These Prompts</span>
                </CardTitle>
                <CardDescription>
                  Click the suggestion buttons or type your own questions!
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="p-3 bg-blue-50 rounded-lg">
                    <p className="font-medium text-blue-800">💡 "Help me plan my morning"</p>
                    <p className="text-sm text-blue-600">Get a personalized schedule</p>
                  </div>
                  
                  <div className="p-3 bg-green-50 rounded-lg">
                    <p className="font-medium text-green-800">📅 "Create a schedule for today"</p>
                    <p className="text-sm text-green-600">Generate an exportable schedule</p>
                  </div>
                  
                  <div className="p-3 bg-purple-50 rounded-lg">
                    <p className="font-medium text-purple-800">😰 "I'm feeling overwhelmed"</p>
                    <p className="text-sm text-purple-600">Get encouragement and tips</p>
                  </div>
                  
                  <div className="p-3 bg-orange-50 rounded-lg">
                    <p className="font-medium text-orange-800">🎵 "Make chores more fun"</p>
                    <p className="text-sm text-orange-600">Get creative suggestions</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <span>📊</span>
                  <span>Demo User Stats</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4">
                  <div className="text-center p-3 bg-gray-50 rounded">
                    <p className="text-xl font-bold text-green-600">${mockUser.weeklyEarnings}</p>
                    <p className="text-sm text-gray-600">Weekly Earnings</p>
                  </div>
                  <div className="text-center p-3 bg-gray-50 rounded">
                    <p className="text-xl font-bold text-blue-600">{mockUser.completionRate}%</p>
                    <p className="text-sm text-gray-600">Success Rate</p>
                  </div>
                </div>
                
                <div className="mt-4">
                  <p className="text-sm font-medium text-gray-700 mb-2">Today's Chores:</p>
                  <div className="space-y-1">
                    {mockChores.map((chore) => (
                      <div key={chore.id} className="flex justify-between text-sm">
                        <span className="text-gray-600">{chore.title}</span>
                        <span className="font-medium text-green-600">${chore.reward}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Chorbit Chat */}
          <div>
            <ChorbieChat
              userId={mockUser.id}
              userRole={mockUser.role}
              userName={mockUser.name}
              currentChores={mockChores}
              weeklyEarnings={mockUser.weeklyEarnings}
              completionRate={mockUser.completionRate}
              onScheduleGenerated={handleScheduleGenerated}
              onExportRequest={handleExportRequest}
            />
          </div>
        </div>

        {/* Features Preview */}
        <div className="mt-12">
          <Card className="bg-gradient-to-r from-indigo-500 to-purple-600 text-white">
            <CardContent className="p-8">
              <div className="text-center">
                <h3 className="text-2xl font-bold mb-4">🚀 Chorbie Features</h3>
                <div className="grid md:grid-cols-3 gap-6">
                  <div>
                    <div className="text-3xl mb-2">🧠</div>
                    <h4 className="font-semibold mb-1">Smart Scheduling</h4>
                    <p className="text-indigo-100 text-sm">
                      AI creates personalized schedules based on your preferences and available time
                    </p>
                  </div>
                  <div>
                    <div className="text-3xl mb-2">📱</div>
                    <h4 className="font-semibold mb-1">iPhone Integration</h4>
                    <p className="text-indigo-100 text-sm">
                      Export schedules directly to iOS Calendar and Reminders
                    </p>
                  </div>
                  <div>
                    <div className="text-3xl mb-2">💪</div>
                    <h4 className="font-semibold mb-1">Motivation Coach</h4>
                    <p className="text-indigo-100 text-sm">
                      Get encouragement and tips to stay motivated and build great habits
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Instructions */}
        <div className="mt-8 text-center">
          <p className="text-gray-600">
            💡 <strong>Note:</strong> Make sure you've added your OpenAI API key to the .env file to see Chorbie in action!
          </p>
        </div>
      </div>
    </div>
  )
} 